import type { ReviewerSecurityIncidentDetail } from '@airdrop/contracts';

import type { ReviewSessionController } from '../../lib/review-session.js';
import type { SecurityReviewApiClient } from '../../lib/security-review-api-client.js';
import { formatReviewDate } from './failed-ai-run-list.js';
import { displayReviewValue } from './safe-review-text.js';

export type SecurityIncidentDetailState = { readonly status: 'loading' | 'forbidden' | 'not_found' | 'failed' } | { readonly status: 'ready'; readonly detail: ReviewerSecurityIncidentDetail };

export function SecurityIncidentDetail({ detail }: { readonly detail: ReviewerSecurityIncidentDetail }) { const { incident } = detail; const decisions = [...detail.decisions].sort((left, right) => left.incidentVersion - right.incidentVersion); return <div className="review-detail"><section className="review-panel" aria-labelledby="security-incident-heading"><div className="review-panel-heading"><div><h1 id="security-incident-heading">安全事件</h1><p>保护性处置保持独立：高机会不降低安全风险。</p></div><span className="review-badge">{incident.state}</span></div><dl className="review-metadata"><Metadata label="事件 ID" value={incident.incidentId} literal /><Metadata label="目标" value={`${incident.target.type} · ${incident.target.id}`} literal /><Metadata label="类别" value={incident.category} literal /><Metadata label="当前处置" value={incident.currentPosture ?? '已解决'} literal /><Metadata label="当前严重性" value={incident.currentSeverity} literal /><Metadata label="当前版本" value={String(incident.incidentVersion)} literal /><Metadata label="公开摘要" value={incident.publicSummary} /><Metadata label="打开时间" value={formatReviewDate(incident.openedAt)} literal /></dl></section><section className="review-panel" aria-labelledby="security-incident-indicators"><h2 id="security-incident-indicators">关联指标</h2>{detail.indicatorIds.length === 0 ? <p className="review-state">尚无关联指标。</p> : <ul className="review-history">{detail.indicatorIds.map((id) => <li key={id}>{id}</li>)}</ul>}</section><section className="review-panel" aria-labelledby="security-incident-history"><h2 id="security-incident-history">不可变更的事件历史</h2>{decisions.length === 0 ? <p className="review-state">尚无事件决策。</p> : <ol className="review-history">{decisions.map((decision) => <li key={decision.decisionId}><div className="review-history-heading"><strong>v{decision.incidentVersion} · {decision.action}</strong><time dateTime={decision.createdAt}>{formatReviewDate(decision.createdAt)}</time></div><p>{decision.reasonCode}</p><p>处置：{decision.resultingPosture ?? '已解决'} · 严重性：{decision.resultingSeverity}</p><p>{displayReviewValue(decision.publicSummary)}</p><p>Evidence ID：{decision.evidenceId}</p><p>{decision.note === null ? '无内部备注' : displayReviewValue(decision.note)}</p></li>)}</ol>}</section></div>; }
export async function loadSecurityIncidentDetail({ session, api, incidentId, redirect }: { readonly session: ReviewSessionController; readonly api: SecurityReviewApiClient; readonly incidentId: string; readonly redirect: (path: string) => void }): Promise<SecurityIncidentDetailState> { if (await session.getAccessToken() === null) { redirect('/review/sign-in'); return { status: 'loading' }; } const result = await api.getIncident(incidentId); if (result.ok) return { status: 'ready', detail: result.data }; if (result.state === 'sign_in_required') { await session.signOut(); redirect('/review/sign-in'); return { status: 'loading' }; } if (result.state === 'forbidden') { await session.signOut(); return { status: 'forbidden' }; } if (result.state === 'not_found') return { status: 'not_found' }; return { status: 'failed' }; }
function Metadata({ label, value, literal = false }: { readonly label: string; readonly value: string; readonly literal?: boolean }) { return <div><dt>{label}</dt><dd>{literal ? value : displayReviewValue(value)}</dd></div>; }
