'use client';

import type { SecurityIndicatorDisclosureCommandV1, SecurityIndicatorDisclosureDecision, SecurityIndicatorDisclosureReasonCode } from '@airdrop/contracts';
import { securityIndicatorDisclosureCommandV1Schema } from '@airdrop/contracts';
import { useRef, useState, type FormEvent } from 'react';

import { createPendingActionGate, type PendingActionGate } from '../../lib/review-pending-action.js';
import type { SecurityReviewApiClient } from '../../lib/security-review-api-client.js';
import type { SecuritySubmissionState } from './security-candidate-detail.js';

export interface IndicatorDisclosureDraft { readonly indicatorId: string; readonly expectedIndicatorVersion: string; readonly decision: SecurityIndicatorDisclosureDecision; readonly reasonCode: SecurityIndicatorDisclosureReasonCode; readonly note: string; }
export function SecurityIndicatorDisclosureForm({ api, indicatorId, onRefresh, onSessionExpired }: { readonly api: SecurityReviewApiClient; readonly indicatorId: string; readonly onRefresh: () => Promise<void>; readonly onSessionExpired: () => void }) { const [draft, setDraft] = useState<IndicatorDisclosureDraft>({ indicatorId, expectedIndicatorVersion: '', decision: 'publish', reasonCode: 'safe_for_public_warning', note: '' }); const [state, setState] = useState<SecuritySubmissionState>({ status: 'idle' }); const gate = useRef(createPendingActionGate()); const disabled = state.status === 'submitting'; async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setState({ status: 'submitting' }); setState(await submitIndicatorDisclosureOnce(gate.current, { api, draft, refresh: onRefresh, sessionExpired: onSessionExpired })); } return <form className="review-form" onSubmit={(event) => { void submit(event); }}><p>当前投影不提供指标版本。请从当前受保护记录核对后手工输入正整数版本；系统不会自动推导、递增或在冲突后重试。</p><input type="hidden" value={indicatorId} readOnly /><Text label="当前指标版本" value={draft.expectedIndicatorVersion} disabled={disabled} onChange={(expectedIndicatorVersion) => setDraft((value) => ({ ...value, expectedIndicatorVersion }))} /><Field label="公开处置"><select value={draft.decision} disabled={disabled} onChange={(event) => setDraft((value) => ({ ...value, decision: event.currentTarget.value as SecurityIndicatorDisclosureDecision, reasonCode: event.currentTarget.value === 'publish' ? 'safe_for_public_warning' : 'sensitive_indicator' }))}><option value="publish">允许公开安全提示</option><option value="withdraw">撤回公开安全提示</option></select></Field><Field label="原因"><select value={draft.reasonCode} disabled={disabled} onChange={(event) => setDraft((value) => ({ ...value, reasonCode: event.currentTarget.value as SecurityIndicatorDisclosureReasonCode }))}>{reasonsFor(draft.decision).map((reason) => <option key={reason} value={reason}>{reason}</option>)}</select></Field><Text label="内部备注（可选）" value={draft.note} disabled={disabled} onChange={(note) => setDraft((value) => ({ ...value, note }))} multiline />{state.message === undefined ? null : <p className={`review-message${state.status === 'saved' ? '' : ' review-message-error'}`} role={state.status === 'saved' ? 'status' : 'alert'}>{state.message}</p>}<button className="review-button" type="submit" disabled={disabled}>{disabled ? '正在提交…' : '提交披露决定'}</button></form>; }
export function buildIndicatorDisclosureCommand(draft: IndicatorDisclosureDraft): SecurityIndicatorDisclosureCommandV1 | null { const parsed = securityIndicatorDisclosureCommandV1Schema.safeParse({ version: 1, indicatorId: draft.indicatorId, expectedIndicatorVersion: Number(draft.expectedIndicatorVersion), decision: draft.decision, reasonCode: draft.reasonCode, note: nullIfEmpty(draft.note) }); return parsed.success ? parsed.data : null; }
export async function submitIndicatorDisclosureOnce(gate: PendingActionGate, input: { readonly api: SecurityReviewApiClient; readonly draft: IndicatorDisclosureDraft; readonly refresh: () => Promise<void>; readonly sessionExpired: () => void }): Promise<SecuritySubmissionState> { if (!gate.begin()) return { status: 'submitting' }; try { const command = buildIndicatorDisclosureCommand(input.draft); if (command === null) return { status: 'failed', message: '请填写当前指标版本和有效的披露决定。' }; const result = await input.api.setIndicatorDisclosure(command.indicatorId, command); if (result.ok) { await input.refresh(); return { status: 'saved', message: '指标披露决定已保存，详情已刷新。' }; } if (result.state === 'sign_in_required' || result.state === 'forbidden') { input.sessionExpired(); return { status: 'forbidden', message: '当前账号没有有效的审核权限。' }; } if (result.state === 'conflict' && result.code === 'security_version_conflict') { await input.refresh(); return { status: 'conflict', message: '安全记录已更新，请检查最新版本后重新提交。' }; } return { status: 'failed', message: '指标披露决定暂时无法提交。请刷新后重试。' }; } finally { gate.finish(); } }
function reasonsFor(decision: SecurityIndicatorDisclosureDecision): readonly SecurityIndicatorDisclosureReasonCode[] { return decision === 'publish' ? ['safe_for_public_warning'] : ['sensitive_indicator', 'disclosure_no_longer_needed']; }
function nullIfEmpty(value: string): string | null { const trimmed = value.trim(); return trimmed === '' ? null : trimmed; }
function Field({ label, children }: { readonly label: string; readonly children: React.ReactNode }) { return <div className="review-field"><label>{label}</label>{children}</div>; }
function Text({ label, value, disabled, onChange, multiline = false }: { readonly label: string; readonly value: string; readonly disabled: boolean; readonly onChange: (value: string) => void; readonly multiline?: boolean }) { return <div className="review-field"><label>{label}</label>{multiline ? <textarea value={value} disabled={disabled} onChange={(event) => onChange(event.currentTarget.value)} /> : <input inputMode="numeric" value={value} disabled={disabled} onChange={(event) => onChange(event.currentTarget.value)} />}</div>; }
