'use client';

import type { ReviewerSecurityIncidentListItem, SecurityIncidentListQuery, SecurityIncidentState, SecurityTargetType } from '@airdrop/contracts';
import Link from 'next/link';

import type { ReviewSessionController } from '../../lib/review-session.js';
import type { SecurityReviewApiClient } from '../../lib/security-review-api-client.js';
import { formatReviewDate } from './failed-ai-run-list.js';
import { displayReviewValue } from './safe-review-text.js';

export type SecurityIncidentListState = { readonly status: 'loading' | 'forbidden' | 'failed' } | { readonly status: 'ready'; readonly items: ReviewerSecurityIncidentListItem[]; readonly nextCursor: string | null };
type StateFilter = 'all' | SecurityIncidentState; type TargetFilter = 'all' | SecurityTargetType;

export function SecurityIncidentList({ state, query, onQueryChange, onNext }: { readonly state: SecurityIncidentListState; readonly query: SecurityIncidentListQuery; readonly onQueryChange?: (query: SecurityIncidentListQuery) => void; readonly onNext?: (cursor: string) => void }) { return <section className="review-panel" aria-labelledby="security-incident-list-heading"><div className="review-panel-heading"><div><h1 id="security-incident-list-heading">安全事件</h1><p>事件历史不可变更；当前处置不会消除既有风险记录。</p></div><div className="review-filters"><label htmlFor="incident-state">状态</label><select id="incident-state" value={query.state} onChange={(event) => onQueryChange?.(changeSecurityIncidentFilters(query, { state: event.currentTarget.value as StateFilter }))}><option value="all">全部状态</option><option value="active">进行中</option><option value="resolved">已解决</option></select><label htmlFor="incident-target">目标</label><select id="incident-target" value={query.targetType} onChange={(event) => onQueryChange?.(changeSecurityIncidentFilters(query, { targetType: event.currentTarget.value as TargetFilter }))}><option value="all">全部目标</option><option value="project">项目</option><option value="source">来源</option></select></div></div>{body(state)}{state.status === 'ready' && state.nextCursor !== null ? <div className="review-pagination"><button className="review-button review-button-secondary" type="button" onClick={() => onNext?.(state.nextCursor ?? '')}>下一页</button></div> : null}</section>; }

export async function loadSecurityIncidentList({ session, api, query, redirect }: { readonly session: ReviewSessionController; readonly api: SecurityReviewApiClient; readonly query: SecurityIncidentListQuery; readonly redirect: (path: string) => void }): Promise<SecurityIncidentListState> { if (await session.getAccessToken() === null) { redirect('/review/sign-in'); return { status: 'loading' }; } const result = await api.listIncidents(query); if (result.ok) return { status: 'ready', items: result.data.items, nextCursor: result.nextCursor }; if (result.state === 'sign_in_required') { await session.signOut(); redirect('/review/sign-in'); return { status: 'loading' }; } if (result.state === 'forbidden') { await session.signOut(); return { status: 'forbidden' }; } return { status: 'failed' }; }
export function changeSecurityIncidentFilters(query: SecurityIncidentListQuery, filters: Partial<Pick<SecurityIncidentListQuery, 'state' | 'targetType'>>): SecurityIncidentListQuery { return { ...query, ...filters, cursor: null }; }
export function applySecurityIncidentCursor(query: SecurityIncidentListQuery, cursor: string): SecurityIncidentListQuery { return { ...query, cursor }; }
function body(state: SecurityIncidentListState) { if (state.status !== 'ready') { if (state.status === 'loading') return <p className="review-state">正在确认审核会话…</p>; if (state.status === 'forbidden') return <p className="review-state review-message-error" role="alert">当前账号没有有效的审核权限。</p>; return <p className="review-state review-message-error" role="alert">安全事件暂时无法加载。请稍后重试。</p>; } if (state.items.length === 0) return <p className="review-state">没有匹配的安全事件。</p>; return <div className="review-table-wrap"><table className="review-table"><thead><tr><th>状态</th><th>类别</th><th>目标</th><th>严重性</th><th>公开摘要</th><th>最后更新</th></tr></thead><tbody>{state.items.map((item) => <tr key={item.incidentId}><td><Link className="review-link" href={`/review/security/incidents/${item.incidentId}`}>{item.state}</Link></td><td>{item.category}</td><td>{item.target.type} · {item.target.id}</td><td>{item.currentSeverity}</td><td>{displayReviewValue(item.publicSummary)}</td><td><time dateTime={item.lastDecisionAt}>{formatReviewDate(item.lastDecisionAt)}</time></td></tr>)}</tbody></table></div>; }
